global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bot'
    static_configs:
      - targets: ['172.17.0.1:8091']
    metrics_path: /metrics

  - job_name: 'scrapper'
    static_configs:
      - targets: ['172.17.0.1:8081']
    metrics_path: /metrics
