global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bot'
    static_configs:
      - targets: ['bot:8091']
    metrics_path: /metrics

  - job_name: 'scrapper'
    static_configs:
      - targets: ['scrapper:8081']
    metrics_path: /metrics
